baseURL = "/"
canonifyurls = true
defaultContentLanguage = "ja"
googleAnalytics = "UA-192815250-1"
languageCode = "en-us"
paginate = 7
theme = "hugo-tranquilpeak-theme"
title = "アイルランドの日本人 Life"
[author]
bio = "Super bio with markdown support **COOL**"
gravatarEmail = "rieringomikan@gmail.com"
job = "Rie"
location = "Ireland"
name = "アイルランドの日本人 Life"
picture = "https://cdn1.iconfinder.com/data/icons/ninja-things-1/1772/ninja-simple-512.png"
[[menu.main]]
identifier = "お問い合わせ"
name = "プロフィール"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
url = "/about"
weight = 6
[[menu.main]]
identifier = "すべての記事"
name = "すべての記事"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-archive\"></i>"
url = "/archives"
weight = 5
[[menu.main]]
identifier = "まだまだ英語は難しい"
name = "まだまだ英語は難しい"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
url = "/categories/まだまだ英語は難しい/"
weight = 4
[[menu.main]]
identifier = "アイルランドで日本語を考える"
name = "日本語を考える"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
url = "/categories/アイルランドで日本語を考える/"
weight = 3
[[menu.main]]
identifier = "アイルランドで暮らす"
name = "アイルランドで暮らす"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
url = "/categories/アイルランドで暮らす/"
weight = 2
[[menu.main]]
identifier = "home"
name = "Home"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
url = "/"
weight = 1
[[menu.misc]]
identifier = "rss"
name = "RSS"
pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
url = "/index.xml"
weight = 1
[params]
autoThumbnailImage = true
clearReading = false
coverImage = "images/cover.jpg"
dateFormat = "2006.January.2"
description = "Riastra"
hierarchicalCategories = false
imageGallery = true
sidebarBehavior = 2
syntaxHighlighter = "highlight.js"
thumbnailImage = true
thumbnailImagePosition = "bottom"
[params.header.rightLink]
class = ""
icon = ""
url = "/about"
[params.sidebar.profile]
url = "/"
[[params.customCSS]]
href = "css/riastra.css"
[[params.sharingOptions]]
icon = "fa-twitter"
name = "Twitter"
url = "https://twitter.com/intent/tweet?text=%s"
[permalinks]
post = "/:year/:month/:slug/"
[taxonomies]
archive = "archives"
category = "categories"
tag = "tags"
